services:
  backend:
    build: .
    container_name: maths_yaka_backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
    # Sleep for 10 seconds to let Postgres wake up
    command: sh -c "sleep 10 && npx prisma generate && npx prisma migrate deploy && npm start"

  db:
    image: postgres:15
    container_name: maths_yaka_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lps1977$
      POSTGRES_DB: videos
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
